<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [54]:
#https://stackoverflow.com/questions/2397141/how-to-initialize-a-two-dimensional-array-in-python

def matrix_mul(A,B):
    
    #checking if the sizes of the two arrays is same
    if len(A[0]) == len(B):
        
        #the result list
        result = []
        
        # making result a list of list 
        result = [[0] * len(B[0]) for _ in range(len(A))]
            
        #performing multiplication
        for i in range(len(A)):
            for j in range(len(B[0])):
                for k in range(len(A[0])):
                    result[i][j] += A[i][k] * B[k][j]
                    
        return result
    
    else:
        
        result = "A*B =Not possible"
        return result
        
A = [[1, 3, 4],[2, 5, 7],[5, 9, 6]]
B = [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        
result = matrix_mul(A, B)
print(result)

A   = [[1,2],[3,4]]  
B   = [[1,2,3,4,5],[5,6,7,8,9]]

result = matrix_mul(A, B)
print(result)

A   = [[1,2],[3,4]]
B   = [[1,4],[5,6],[7,8],[9,6]]

result = matrix_mul(A, B)
print(result)

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]
[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]
A*B =Not possible


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [47]:
#https://stackoverflow.com/a/15889203

from random import uniform
from itertools import accumulate
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]

# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    
    # your code here for picking an element from with the probability propotional to its magnitude
    
    Sum =0.0
    for x in A:
        Sum += x
        
    Nor_Sum = [x/Sum for x in A]
    
    Cum_Nor_Sum = list(accumulate(Nor_Sum))
    r = uniform(0,1)
    
    for i in Cum_Nor_Sum:
        if r <= i:
            n = Cum_Nor_Sum.index(i)
            return A[n]
    

def sampling_based_on_magnitued(A):
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued(A)

100
100
79
79
79
100
45
100
100
45
79
45
13
100
79
13
27
100
45
13
100
79
79
79
45
100
100
79
6
5
100
79
79
100
27
100
100
100
6
45
45
100
100
79
27
100
100
28
100
79
100
27
45
79
28
100
27
100
100
100
79
45
79
45
28
45
45
100
45
100
28
13
100
13
45
100
45
28
100
100
79
13
10
13
27
6
45
100
100
100
27
100
45
79
27
79
28
79
100


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [38]:
import re

def replace_digits(String):
            
    String = re.sub("[^0-9]", "", String)
    String = String.replace(String, len(String)*'#')
    return String

result = replace_digits("234")
print(result)

result = replace_digits("a2b3c4")
print(result)

result = replace_digits("abc")
print(result)

result = replace_digits("#2a$#b%c%561#")
print(result)

###
###

####


<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [35]:
#https://stackoverflow.com/questions/529424/traverse-a-list-in-reverse-order-in-python
#https://stackoverflow.com/questions/3121979/how-to-sort-list-tuple-of-lists-tuples-by-the-element-at-a-given-index
#https://stackoverflow.com/questions/20577840/python-dictionary-sorting-in-descending-order-based-on-values/41866830
import math

Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

def percentile(marks, percentile):
    return marks[int(math.ceil((len(marks) * percentile) / 100)) - 1]

def display_dash_board(students, marks):
    
    records_tuple = list(zip(students,marks))
    
    records_tuple = sorted(records_tuple, key=lambda tup: tup[1], reverse = True)

    # write code for computing top top 5 students
    print("a.")
    top_5_students = records_tuple[:5]
    for i in top_5_students:
        print(i[0], i[1])
    
    # write code for computing top least 5 students
    print("\nb.")
    least_5_students = records_tuple[:4:-1]
    for i in least_5_students:
        print(i[0], i[1])
    
    # write code for students_within_25_and_75
    
    percentile_25 = percentile(sorted(marks),25)
    percentile_75 = percentile(sorted(marks),75)
    
    print("\nc.")
    for i in reversed(records_tuple):
        if i[1] >= percentile_25 and i[1] < percentile_75:
            print(i[0], i[1])
    
display_dash_board(Students, Marks)

a.
student8 98
student10 80
student2 78
student5 48
student7 47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [3]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    closest_points = []
    top_limit = 5
    for i in S:
        
        #finding euclidean distance
        a = i[0]*P[0] + i[1]*P[1]
        b = math.sqrt(i[0]**2 + i[1]**2) 
        c = math.sqrt(P[0]**2 + P[1]**2)
        d = b * c 
        e = a/d
        f = math.acos(e)
        
        closest_points.append(f)
        
    closest_points_dict = {j:i for i,j in enumerate(closest_points)}
    closest_points_dict = sorted(closest_points_dict.items())
    
    for i in range(0,top_limit):
        print(S[closest_points_dict[i][1]])
    
    #return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
closest_points_to_p(S, P)
#nt the returned values

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [31]:
import math
import re

# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    
    red_dist = []
    blue_dist = []
    
    #extracting all the coefficients
    #https://stackoverflow.com/questions/56948506/how-to-extract-coefficients-from-a-line-equation-in-python-without-using-numpy
    z = re.findall(r'[\d\.\-\+]+', line)
    #keeing all the values in float
    z = list(map(float, z))
    
    #calculating the cosine distance for red and blue group
    for i in red:
        dist = (z[0]*i[0] + z[1]*i[1] + z[2])/ math.sqrt(z[0]**2 + z[1]**2)
        red_dist.append(dist)
        
    for i in blue:
        dist = (z[0]*i[0] + z[1]*i[1] + z[2])/ math.sqrt(z[0]**2 + z[1]**2)
        blue_dist.append(dist) 
        
    #converting red and blue dist group to boolean values
    for i in range(len(red_dist)):
        if red_dist[i] > 0:
            red_dist[i] = 1
        elif red_dist[i] < 0:
            red_dist[i] = 0
        else:
            return 'NO'
            
    for i in range(len(blue_dist)):
        if blue_dist[i] > 0:
            blue_dist[i] = 1
        elif blue_dist[i] < 0:
            blue_dist[i] = 0
        else:
            return 'NO'
            
    sum_red_dist = sum(red_dist)
    sum_blue_dist = sum(blue_dist)
            
    if sum_red_dist + sum_blue_dist == 5:
        return 'YES'
    else:
        return 'NO'
            

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no)

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [37]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    string = string.split(",")
    len_str = len(string)
    
    Num = 0
    j = -1
    i = 0
    
    while j < len_str - 1: 
        j = j + 1
        if string[j] != '_':
            Num = Num + int(string[j])
            Num = Num / ((j-i) + 1)
            for x in range(i, j+1):
                string[x] = int(Num)
            i = j
            continue
    Num = Num / ((j-i) + 1)
    for x in range(i, j+1):
        string[x] = int(Num)
       
    #https://stackoverflow.com/questions/5618878/how-to-convert-list-to-string
    str1 = ','.join(str(e) for e in string)
    print("Output: ",str1)
    print("\n")
        
S=  "_,_,_,24"
print("Input: ", S)
curve_smoothing(S)
S=  "40,_,_,_,60"
print("Input: ", S)
curve_smoothing(S)
S=  "80,_,_,_,_"
print("Input: ", S)
curve_smoothing(S)
S=  "_,_,30,_,_,_,50,_,_"
print("Input: ", S)
curve_smoothing(S)

Input:  _,_,_,24
Output:  6,6,6,6


Input:  40,_,_,_,60
Output:  20,20,20,20,20


Input:  80,_,_,_,_
Output:  16,16,16,16,16


Input:  _,_,30,_,_,_,50,_,_
Output:  10,10,12,12,12,12,4,4,4




<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [27]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
from fractions import Fraction

def compute_conditional_probabilites(A):
    
    #sd will keep the count of S in a dictionary format
    sd = dict()
    #td will keep count of number of unique tuples in a dictionary
    td = dict()
    
    #s_occurence will keep all occurences of S in the input
    #tuple_occurence will keep the  input in a tuple format
    s_occurence = []
    tuple_occurence = []
    
    s = ['S1', 'S2', 'S3']
    
    print_helper = [('F1', 'S1'), ('F1', 'S2'), ('F1', 'S3'), ('F2', 'S1'),
                    ('F2', 'S2'), ('F2', 'S3'), ('F3', 'S1'), ('F3', 'S2'),
                    ('F3', 'S3'), ('F4', 'S1'), ('F4', 'S2'), ('F4', 'S3'),
                    ('F5', 'S1'), ('F5', 'S2'), ('F5', 'S3')]
    
    
    for elment in A:
        s_occurence.append(elment[1])
        tuple_occurence.append(tuple(elment))
        
    for element in s:
        sd[element] = s_occurence.count(element)
    print(sd)
        
    for element in print_helper:
        td[element] = tuple_occurence.count(element)
    print(td)
    
    for element in print_helper:
       print("P(F={}|S=={}) = ".format(element[0],element[1]),Fraction(td[element],sd[element[1]]))

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

{'S1': 4, 'S2': 3, 'S3': 3}
{('F1', 'S1'): 1, ('F1', 'S2'): 1, ('F1', 'S3'): 0, ('F2', 'S1'): 1, ('F2', 'S2'): 1, ('F2', 'S3'): 1, ('F3', 'S1'): 0, ('F3', 'S2'): 1, ('F3', 'S3'): 1, ('F4', 'S1'): 1, ('F4', 'S2'): 0, ('F4', 'S3'): 1, ('F5', 'S1'): 1, ('F5', 'S2'): 0, ('F5', 'S3'): 0}
P(F=F1|S==S1) =  1/4
P(F=F1|S==S2) =  1/3
P(F=F1|S==S3) =  0
P(F=F2|S==S1) =  1/4
P(F=F2|S==S2) =  1/3
P(F=F2|S==S3) =  1/3
P(F=F3|S==S1) =  0
P(F=F3|S==S2) =  1/3
P(F=F3|S==S3) =  1/3
P(F=F4|S==S1) =  1/4
P(F=F4|S==S2) =  0
P(F=F4|S==S3) =  1/3
P(F=F5|S==S1) =  1/4
P(F=F5|S==S2) =  0
P(F=F5|S==S3) =  0


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [43]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    
    words_S1 = S1.split()
    words_S2 = S2.split()
    
    common = set(words_S1).intersection(set(words_S2))
    a = len(common)
    print(a)
    
    b = set(words_S1).difference(set(words_S2))
    print(b)
    
    c = set(words_S2).difference(set(words_S1))
    print(c)
    #return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
string_features(S1, S2)
#print(#the above values)

7
{'first', '5', 'F'}
{'3', 'second', 'S'}


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [105]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math
import numpy as np

# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    
    len_A = len(A)
    x = 0
    result = 0
    
    while x < len_A:
        comp_1 = A[x][0] * math.log10(A[x][1]) 
        comp_2 = (1 - A[x][0]) * math.log10(1 - A[x][1]) 
        comp_3 = comp_1 + comp_2
        result = result + comp_3
        x = x + 1
    result = -(result / len_A)
    
    return result

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
